# Generated by Django 4.2.19 on 2025-02-28 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codesnippet",
            name="created_at",
        ),
        migrations.AddField(
            model_name="codesnippet",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.problem",
            ),
        ),
    ]
