# Generated by Django 4.2.19 on 2025-02-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_codesnippet_created_at_codesnippet_problem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codesnippet",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.problem"
            ),
        ),
    ]
